AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RuboCopStyle/Documentation:
  Enabled: false

Naming/FileName:
  Enabled: false
